### PR TITLE
Do not capture child future in TaskGroup::spawn's returned future

### LINKED ISSUE #3: Parent future is too big in memory
If a parent future spawns a child future with `TaskGroup::spawn`, the memory used by the child is included in the memory used by the parent.

Example
```rust
use std::mem::size_of_val;

use task_group::TaskGroup;

fn main() {
    assert_eq!(size_of_val(&big_future()), 4098);
    assert_eq!(size_of_val(&empty_future()), 1);
    assert_eq!(
        size_of_val(&spawns_big_future_using_tokio()),
        size_of_val(&spawns_empty_future_using_tokio())
    );

    assert_eq!(
        size_of_val(&spawns_big_future_using_task_group()),
        size_of_val(&spawns_empty_future_using_task_group())
    );
    // ^ Fails
    // thread 'main' panicked at 'assertion failed: `(left == right)`
    //   left: `4368`,
    //   right: `272`', src/main.rs:13:5
}

async fn spawns_big_future_using_task_group() {
    let (task_group, task_manager) = TaskGroup::new();
    task_group.spawn("big future", big_future()).await.unwrap();
    drop(task_group);
    task_manager.await.unwrap();
}

async fn spawns_empty_future_using_task_group() {
    let (task_group, task_manager) = TaskGroup::new();
    task_group
        .spawn("empty future", empty_future())
        .await
        .unwrap();
    drop(task_group);
    task_manager.await.unwrap();
}

async fn spawns_big_future_using_tokio() {
    tokio::spawn(big_future()).await.unwrap().unwrap();
}

async fn spawns_empty_future_using_tokio() {
    tokio::spawn(empty_future()).await.unwrap().unwrap();
}

async fn big_future() -> Result<(), ()> {
    let big_object = [0_u8; 4096];
    // Hold _big_object across an await point
    async { () }.await;
    drop(big_object);
    Ok(())
}

async fn empty_future() -> Result<(), ()> {
    Ok(())
}
```

I believe this is caused by TaskGroup::spawn being an async function, so all the arguments are represented in the async function's initial state. This can be fixed by switching it to a normal function that returns `impl Future`, and starting the async block after the task has been spawned.

PS: thanks for this awesome library!

### PR DESCRIPTION
**Pull request by pchickey**
Closes #3 

This PR follows @timotree3's suggestion in #3 to change the implementation of TaskGroup::{spawn, spawn_on, spawn_local} so that the Future returned by those methods is smaller in size, by not capturing the child Future.

I added a regression check based on the bug report, replacing the hard-coded sizes with a greater-than assertion to hopefully be less fragile if something in Rust changes. Still, I'm not sure how fragile this might be, since I don't understand enough about the assumptions rustc and LLVM can make about these values, and how those might change.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -28,49 +28,58 @@ impl<E: Send + 'static> TaskGroup<E> {
...
-    ) -> Result<(), SpawnError> {
+    ) -> impl Future<Output = Result<(), SpawnError>> {
         let name = name.as_ref().to_string();
         let join = tokio::task::spawn(f);
-        match self.new_task.send(ChildHandle { name, join }).await {
-            Ok(()) => Ok(()),
-            // If there is no receiver alive to manage the new task, drop the child in error to
-            // cancel it:
-            Err(_child) => Err(SpawnError::GroupDied),
+        let new_task = self.new_task.clone();
```
Comment (timotree3) [inline src/lib.rs]: I believe you can avoid cloning if you add `+ '_` to the returned future

File: src/lib.rs [hunk 2]
```diff
@@ -505,4 +514,60 @@ mod test {
         assert!(res.is_err(), "timed out");
         assert_eq!(*l.lock().await, vec!["child gonna nap"]);
     }
+
+    // This serves as a regression check for https://github.com/pchickey/task-group/issues/3
+    // I'm not sure how fragile this test will be, since it may
+    // depend on Rust and LLVM's ability to optimize out unused
+    // allocations like big_object.
```
Comment (timotree3) [inline src/lib.rs:518]: A few ideas if it's important to make `big_future` less fragile:
- You could use a function like [`criterion::black_box`](https://docs.rs/criterion/0.3.5/criterion/fn.black_box.html) on big_object after the await point to make sure it never gets optimized out. 
  - If you don't wanna add a dependency, you could print `big_object` after the await point. The print would not show up in test output unless the test failed.
- You could make a struct that holds some data and implements future manually

File: src/lib.rs [hunk 3]
```diff
@@ -505,4 +514,60 @@ mod test {
...
+            tokio::spawn(big_future()).await.unwrap().unwrap();
+        }
+
+        async fn spawns_empty_future_using_tokio() {
+            tokio::spawn(empty_future()).await.unwrap().unwrap();
+        }
+
+        async fn big_future() -> Result<(), ()> {
+            let big_object = [0_u8; 4096];
+            // Hold _big_object across an await point
```
Comment (timotree3) [inline src/lib.rs]: Typo in my original example

```suggestion
            // Hold big_object across an await point
```

**Review by timotree3 — COMMENTED** [review]
Thanks for fixing this so quickly! :)

**Review by aturon — APPROVED** [review]
This is great, thank you!

**Review by aturon — APPROVED** [review]

**Comment by pchickey** [comment]
Published as `0.2.2`: https://crates.io/crates/task-group/0.2.2
